[alias]
b = "build"
br = "build --release"
c = "clippy -- -Wclippy::all -Wclippy::nursery -Wclippy::cargo"
t = "test"  # "-- --nocapture"
tr = "test --release"
r = "run"
rr = "run --release"


[build]
incremental = true


[env]
ASAN_OPTIONS = 'detect_leaks=1,detect_stack_use_after_return=1'


[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true


#[target.x86_64-unknown-linux-gnu]
#runner = 'sudo -E'
